### ISSUE TITLE
date_hour extraction missing in tstat

### ISSUE THREAD

**Issue by jme0** [doksu/thirdman#6]
Hi Douglas
Just had a look a your new v2. As you are using tstats now there's no automatic date_hour extraction  as with raw events, so the eval for the period does not work anymore.
Regards
Jonas

**Comment by doksu** [comment]
Hi Jonas,

Good catch. I ran v2 through the sample events and it was 100% accurate in detecting the third man event and so thought it was fine... (I was wrong!)

As you've noticed, the search will still work but the sensitivity in reduced. If you put this: | eval date_hour=strftime(_time,"%H") immediately before the period eval it should fix it.

I'll patch it tonight and publish v2.0.1 - For the sake of the administrators having to patch it, I hope this is the last bug!

I owe you more than one coffee/beer/etc. Perhaps at conf this year? :)

Cheers,
Doug

**Comment by doksu** [comment]
Patched and app updated on Splunkbase. :)
