### ISSUE TITLE
streamsstats evalution backwards in time

### ISSUE THREAD

**Issue by jme0** [doksu/thirdman#7]
Hi Douglas
Because streamstats seems to evaluate results backwards in time (in the order they are delivered, lot of discussion about this on Splunk Answers) the unique vector is actually increased on the last occurrence of a new value not on the first one in time. Using "reverse" will put the whole thing in right order (hopefully without perfomance impact).

**Comment by jme0** [comment]
Ok issue solved :-),  this seems to be again different with tstats, reverse is not needed as before with the datamodel command. Nice Splunk...

**Comment by doksu** [comment]
Hi Jonas,

It shouldn't be, I actually had a reverse in v1 and had to remove it for v2 because tstats/pivot returns results in the opposite order to normal searches (ie. the datamodel command). Run just the tstats command and check.

Cheers,
Doug
